sudo: false
language: python
services:
  - redis
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
install:
  - pip install -r requirements.txt
script:
  - RUN_SLOW_TESTS_TOO=1 py.test --cov rq --durations=5
after_success:
  - codecov
